# Numpy

In [1]:
import numpy as np

In [2]:
my_array1= np.array([1,2,3,4,5,6])

In [3]:
my_array1

array([1, 2, 3, 4, 5, 6])

In [4]:
#chnge element
my_array1 [2:4] = 12

In [5]:
my_array1

array([ 1,  2, 12, 12,  5,  6])

In [6]:
#For Straight line
my_array1.ravel()

array([ 1,  2, 12, 12,  5,  6])

In [35]:
#for Reshape
my_array1.reshape((6,1))

array([[ 1],
       [ 2],
       [12],
       [12],
       [ 5],
       [ 6]])

In [8]:
#Built in method
#for Sorting -from indexs
my_array1.argsort()

array([0, 1, 4, 5, 2, 3], dtype=int64)

In [9]:
my_array1.shape

(6,)

In [10]:
my_array1.dtype

dtype('int32')

In [11]:
my_array1.size

6

2d array

In [38]:
my_array2= np.array([[1,2,3,4,5,6]])

In [13]:
my_array2[0,3]

4

In [14]:
#Conversion from other Python structures -2D
my_array2 = np.array([[9,12,13],[14,15,16],[17,18,19]])

In [15]:
my_array2

array([[ 9, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [16]:
#for sum of axis
my_array2.sum(axis =0)

array([40, 45, 48])

In [17]:
#for transposition
my_array2.T

array([[ 9, 14, 17],
       [12, 15, 18],
       [13, 16, 19]])

In [18]:
#Built in Method
#squareroot
np.sqrt(my_array2)

array([[3.        , 3.46410162, 3.60555128],
       [3.74165739, 3.87298335, 4.        ],
       [4.12310563, 4.24264069, 4.35889894]])

In [19]:
#for indexing
my_array2[1][2]

16

In [20]:
#Built in fuction for creating array 
#for diagonal value
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [21]:
my_array2.shape

(3, 3)

In [22]:
my_array2.size

9

In [23]:
#Intrinsic NumPy array creation functions

In [24]:
#Built in fuction for creating array 
#for zeros 
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
#arange funtion
rng = np.arange(13)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
#for spacing in array
lspace = np.linspace(11,12,13)
lspace

array([11.        , 11.08333333, 11.16666667, 11.25      , 11.33333333,
       11.41666667, 11.5       , 11.58333333, 11.66666667, 11.75      ,
       11.83333333, 11.91666667, 12.        ])

In [27]:
array_1d = np.ones(4)
print(array_1d)


array_2d_int = np.ones((2, 3), dtype=int)
print(array_2d_int)

[1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [30]:
#Log (input) to the base e=(2.7)
arr=np.array([2,3,4,5,6])
log_value=np.log(arr) 
print(log_value)

[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [31]:
#Exponential function 
#e = 2.7182 (e^X and X=is the value pass by user) 
a = 1
b = np.exp(2)
print (np.log(a))
print (np.log(b))

0.0
2.0


In [32]:
#Log (input) to the base e=(2.7)
import math   
print("Log value: ", math.log(2))

Log value:  0.6931471805599453


In [33]:
#Exponential function 
#e = 2.7182 (e^X and X=is the value pass by user) 
print(math.exp(0))

1.0
